### ISSUE TITLE
Polymorphism on property types is lost once inserted in database

### ISSUE THREAD

**Issue by Amp0** [mathieumack/MvvX.Plugins.CouchBaseLite#11]
### Issue description
Consider this case : 

```C#
public class Foo 
{
    public Bar Bar { get; set; }
}

public class Bar 
{
    public virtual string Value { get; set; }
}

public class AnotherBarType : Bar 
{
    public int NewPropertyOfInheritedType { get; set; }
    public override string Value
    {
        ...
    }
}

var objectToInsert = new Foo()
{
    Bar = new AnotherBarType()
    {
        NewPropertyOfInheritedType = 2,
        Value = "ok"
    }
};
```
When inserting the object in the database the object will have the property serialized as an `AnotherBarType` type.
But on a get (deserialization) the object type will be `Bar` instead of `AnotherBarType`, and all additional properties will be lost.

### Possible fix

A possible fix would be to make the JsonSerializerSettings accessible from the interface to allow the use of : 
```C#
JsonSerializerSettings settings = new JsonSerializerSettings()
{
    TypeNameHandling = TypeNameHandling.Auto
};
```

This json setting will add to the serialized json the $type property if the type is an inherited type (like `AnotherBarType`) the property contains the namespace + type of the object. If we use the same setting on deserialization it should be able to use the correct type.

Is it already possible to access JsonSerializerSettings ?
It looks like it might be possible to specify a custom serialization/deserialization using views, but I am not really sure about that.

**Comment by mathieumack** [comment]
Closed as the main repository is now on https://github.com/mathieumack/NoSqlRepositories
