### ISSUE TITLE
iOS plugin bootstrap

### ISSUE THREAD

**Issue by NeedNap** [mathieumack/MvvX.Plugins.CouchBaseLite#4]
Hi,
I'm trying to use your plugin for Android and iOS project.

In Android it works fine but in the iOS part I tried to make the same Android bootstrap process (adding the CouchBaseLitePluginBootstrap class inside the Bootstrap folder) and I get the following errors on AppDelegate setup.Initialize():

Could not find plugin loader for type MvvX.Plugins.CouchBaseLite.PluginLoader

What can I do to setup properly the plugin?
I can't find any iOS example on this repository.

**Comment by mathieumack** [comment]
Hi,
Thanks for your message.
I think that the bootstrapper file for iOS is missing or invalid. I will check it and update the repository as soon as possible.

**Comment by mathieumack** [comment]
I, @ArnaudMarcille has fixed the issue.
An update of the plugin is available on nuget.

**Comment by NeedNap** [comment]
Thank you so much: now it works fine!
