### ISSUE TITLE
Add way to Update documents

### ISSUE THREAD

**Issue by Amp0** [mathieumack/MvvX.Plugins.CouchBaseLite#8]
Currently the update is a full update of a document.
We want to be able to update just some fields instead of pushing a new instance/revision every time.

Idea 💡 : 
 - Use a ```Dictionnary<string, object>()``` to update fields (see [documentation](https://developer.couchbase.com/documentation/mobile/current/guides/couchbase-lite/native-api/document/index.html) for CBL implementation)

**Comment by mathieumack** [comment]
Closed as the main repository is now on https://github.com/mathieumack/NoSqlRepositories
